/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./src/features/auth/AuthForm.vue')['default']
    AuthLayout: typeof import('./src/pages/auth/AuthLayout.vue')['default']
    AuthPage: typeof import('./src/pages/auth/AuthPage.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    DemoPage: typeof import('./src/pages/demo/DemoPage.vue')['default']
    FormField: typeof import('./src/shared/FormField.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Typography: typeof import('./src/shared/Typography.vue')['default']
  }
}
