name: Deployment
on:
  push:
    tags:
      - "v*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - name: Install frontend dependencies
        run: bun install
        working-directory: frontend

      - name: Build frontend
        run: bun run build
        working-directory: frontend

      - uses: astral-sh/setup-uv@v7

      - name: Deploy
        run: uv run fastapi deploy
        working-directory: backend
        env:
          FASTAPI_CLOUD_TOKEN: ${{ secrets.FASTAPI_CLOUD_TOKEN }}
          FASTAPI_CLOUD_APP_ID: ${{ secrets.FASTAPI_CLOUD_APP_ID }}
